#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    #- $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
sudo: required
services:
  - docker
dist: trusty
language: java
jdk:
  - oraclejdk8
#  - oraclejdk9
  - openjdk8
#  - openjdk10
env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=256m"
script:
  - ./gradlew build jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - sudo apt install --only-upgrade docker-ce -y
deploy:
  provider: script
#  script: scripts/tag-release.sh && scripts/publish-site-starter.sh && scripts/publish-docker-image.sh
  script: scripts/install.sh
  skip_cleanup: true
  on:
    branch: master
    jdk: oraclejdk8
