version: "3"
services:
  whistlepost:
    image: "micronode/whistlepost:1.1.4"
    ports:
      - "8080:8080"
#    volumes:
#      - ./src/app:/wp/apps/innersource:ro
#      - ./src/content:/wp/content/innersource:ro
