version: "3"
services:
  whistlepost:
    image: "micronode/whistlepost:1.1.5-develop-SNAPSHOT"
    ports:
      - "8080:8080"
    volumes:
      - /mnt/doprod1-docker/innersource/src/app:/wp/apps/innersource:ro
      - /mnt/doprod1-docker/innersource/src/content:/wp/content/innersource:ro

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
